services:
  - type: web
    name: sui-rpc-monitor
    runtime: node
    plan: free
    buildCommand: bun install && bun run build
    startCommand: bun start
    envVars:
      - key: NODE_VERSION
        value: 23.3.0
    headers:
      - path: /api/*
        name: Access-Control-Allow-Origin
        value: "*"
      - path: /api/*
        name: Access-Control-Allow-Methods
        value: GET, POST, OPTIONS
      - path: /api/*
        name: Access-Control-Allow-Headers
        value: X-CSRF-Token, X-Requested-With, Accept, Accept-Version, Content-Length, Content-MD5, Content-Type, Date, X-Api-Version